services:
  postgres:
    image: postgres:15
    container_name: booking-postgres
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: artikunutma1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: booking-redis
    ports:
      - "6379:6379"
    networks:
      - booking-network
    restart: unless-stopped

  booking-app:
    build: .
    container_name: booking-app
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-postgres:5432/bookingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: artikunutma1
      
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      
      SPRING_SESSION_STORE_TYPE: redis
      
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_REDIS: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SESSION: DEBUG
    networks:
      - booking-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  booking-network:
    driver: bridge
